{
 "title": "EC2",
 "time": { "from": "now-6h", "to": "now" },
 "templating": {
  "list": [
   { "name": "datasource", "label": "Datasource", "query": "cloudwatch" },
   { "name": "region", "label": "Region", "query": "regions()" },
   { "name": "period", "label": "Period [sec]", "query": "60,300" }
  ]
 },
 "panels": [
  { "title": "Overview", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  {
   "title": "CPU utilization per instance [%]",
   "type": "graph",
   "gridPos": { "h": 8, "w": 24, "x": 0, "y": 1 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "dimensions": { "InstanceId": "*" },
     "metricName": "CPUUtilization",
     "namespace": "AWS/EC2",
     "period": "$period",
     "region": "$region",
     "statistics": [ "Maximum" ]
    }
   ]
  },
  {
   "title": "Total network traffic outbound (+) and inbound (-) [bytes/sec]",
   "type": "graph",
   "gridPos": { "h": 9, "w": 24, "x": 0, "y": 9 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "alias": "Inbound",
     "dimensions": { "InstanceId": "*" },
     "expression": "SUM(REMOVE_EMPTY(SEARCH('{AWS/EC2,InstanceId} MetricName=\"NetworkIn\"', 'Sum', $period)))/$period",
     "metricName": "NetworkOut",
     "namespace": "AWS/EC2",
     "period": "$period",
     "region": "$region",
     "statistics": [ "Average" ]
    },
    {
     "alias": "Outbound",
     "dimensions": { "InstanceId": "*" },
     "expression": "SUM(REMOVE_EMPTY(SEARCH('{AWS/EC2,InstanceId} MetricName=\"NetworkOut\"', 'Sum', $period)))/$period",
     "metricName": "NetworkOut",
     "namespace": "AWS/EC2",
     "region": "$region",
     "statistics": [ "Average" ]
    }
   ]
  },
  { "title": "Network details", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 18 } },
  {
   "title": "Inbound network traffic per instance [bytes/sec]",
   "type": "graph",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 19 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "dimensions": { "InstanceId": "*" },
     "expression": "REMOVE_EMPTY(SEARCH('{AWS/EC2,InstanceId} MetricName=\"NetworkIn\"', 'Sum', $period))/$period",
     "metricName": "NetworkIn",
     "namespace": "AWS/EC2",
     "period": "$period",
     "region": "$region",
     "statistics": [ "Sum" ]
    }
   ]
  },
  {
   "title": "Outbound network traffic per instance [bytes/sec]",
   "type": "graph",
   "gridPos": { "h": 9, "w": 12, "x": 12, "y": 19 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "dimensions": { "InstanceId": "*" },
     "expression": "REMOVE_EMPTY(SEARCH('{AWS/EC2,InstanceId} MetricName=\"NetworkOut\"', 'Sum', $period))/$period",
     "metricName": "NetworkIn",
     "namespace": "AWS/EC2",
     "period": "$period",
     "region": "$region",
     "statistics": [ "Sum" ]
    }
   ]
  },
  {
   "title": "Inbound network packets per instance [IOPS]",
   "type": "graph",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 28 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "dimensions": { "InstanceId": "*" },
     "expression": "REMOVE_EMPTY(SEARCH('{AWS/EC2,InstanceId} MetricName=\"NetworkPacketsIn\"', 'Sum', $period))/$period",
     "metricName": "NetworkPacketsIn",
     "namespace": "AWS/EC2",
     "region": "$region",
     "statistics": [ "Sum" ]
    }
   ]
  },
  {
   "title": "Outbound network packets per instance [IOPS]",
   "type": "graph",
   "gridPos": { "h": 9, "w": 12, "x": 12, "y": 28 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "dimensions": { "InstanceId": "*" },
     "expression": "REMOVE_EMPTY(SEARCH('{AWS/EC2,InstanceId} MetricName=\"NetworkPacketsOut\"', 'Sum', $period))/$period",
     "metricName": "NetworkPacketsIn",
     "namespace": "AWS/EC2",
     "region": "$region",
     "statistics": [ "Sum" ]
    }
   ]
  },
  { "title": "Disk details", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 37 } },
  {
   "title": "The following metrics are reported for EC2 Instance Store Volumes. For Amazon EBS volumes, see the EBS dashboard.",
   "type": "text",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 38 }
  },
  {
   "title": "Disk READ per instance [bytes/sec]",
   "type": "graph",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 39 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "alias": "{{label}}",
     "dimensions": { "InstanceId": "*" },
     "expression": "REMOVE_EMPTY(SEARCH('{AWS/EC2,InstanceId} MetricName=\"DiskReadBytes\"', 'Sum', $period))/$period",
     "metricName": "DiskReadBytes",
     "namespace": "AWS/EC2",
     "region": "$region",
     "statistics": [ "Sum" ]
    }
   ]
  },
  {
   "title": "Disk WRITE per instance [bytes/sec]",
   "type": "graph",
   "gridPos": { "h": 9, "w": 12, "x": 12, "y": 39 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "alias": "{{label}}",
     "dimensions": { "InstanceId": "*" },
     "expression": "REMOVE_EMPTY(SEARCH('{AWS/EC2,InstanceId} MetricName=\"DiskWriteBytes\"', 'Sum', $period))/$period",
     "metricName": "DiskReadBytes",
     "namespace": "AWS/EC2",
     "region": "$region",
     "statistics": [ "Sum" ]
    }
   ]
  },
  {
   "title": "Disk READ per instance [IOPS]",
   "type": "graph",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 48 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "alias": "{{label}}",
     "dimensions": { "InstanceId": "*" },
     "expression": "REMOVE_EMPTY(SEARCH('{AWS/EC2,InstanceId} MetricName=\"DiskReadOps\"', 'Sum', $period))/$period",
     "metricName": "DiskReadBytes",
     "namespace": "AWS/EC2",
     "region": "$region",
     "statistics": [ "Sum" ]
    }
   ]
  },
  {
   "title": "Disk WRITE per instance [IOPS]",
   "type": "graph",
   "gridPos": { "h": 9, "w": 12, "x": 12, "y": 48 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "alias": "{{label}}",
     "dimensions": { "InstanceId": "*" },
     "expression": "REMOVE_EMPTY(SEARCH('{AWS/EC2,InstanceId} MetricName=\"DiskWriteOps\"', 'Sum', $period))/$period",
     "metricName": "DiskReadBytes",
     "namespace": "AWS/EC2",
     "region": "$region",
     "statistics": [ "Sum" ]
    }
   ]
  },
  {
   "title": "Status Checks",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 57 },
   "collapsed": true,
   "panels": [
    {
     "title": "Status check failed [Sum]",
     "type": "graph",
     "gridPos": { "h": 6, "w": 24, "x": 0, "y": 23 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "dimensions": { "InstanceId": "*" },
       "metricName": "StatusCheckFailed",
       "namespace": "AWS/EC2",
       "period": "$period",
       "region": "$region",
       "statistics": [ "Sum" ]
      }
     ]
    },
    {
     "title": "Instance status check failed [Sum]",
     "type": "graph",
     "gridPos": { "h": 6, "w": 24, "x": 0, "y": 29 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "dimensions": { "InstanceId": "*" },
       "metricName": "StatusCheckFailed",
       "namespace": "AWS/EC2",
       "period": "$period",
       "region": "$region",
       "statistics": [ "Sum" ]
      }
     ]
    },
    {
     "title": "System status check failed [Sum]",
     "type": "graph",
     "gridPos": { "h": 6, "w": 24, "x": 0, "y": 35 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "dimensions": { "InstanceId": "*" },
       "metricName": "StatusCheckFailed",
       "namespace": "AWS/EC2",
       "period": "$period",
       "region": "$region",
       "statistics": [ "Sum" ]
      }
     ]
    }
   ]
  }
 ]
}