{
 "title": "Logs",
 "time": { "from": "now-6h", "to": "now" },
 "templating": {
  "list": [
   { "name": "datasource", "label": "Datasource", "query": "cloudwatch" },
   { "name": "region", "label": "Region", "query": "regions()" },
   { "name": "period", "label": "Period [sec]", "query": "60,300" }
  ]
 },
 "panels": [
  {
   "title": "Incoming log events [count/sec]",
   "type": "graph",
   "gridPos": { "h": 8, "w": 24, "x": 0, "y": 0 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "dimensions": { "LogGroupName": "*" },
     "expression": "REMOVE_EMPTY(SEARCH('{AWS/Logs,LogGroupName} MetricName=\"IncomingLogEvents\"', 'Sum', $period))/$period",
     "metricName": "IncomingLogEvents",
     "namespace": "AWS/Logs",
     "period": "$period",
     "region": "$region",
     "statistics": [ "Sum" ]
    }
   ]
  },
  {
   "title": "Incoming bytes [bytes/sec]",
   "type": "graph",
   "gridPos": { "h": 8, "w": 24, "x": 0, "y": 8 },
   "yaxes": [
    { "format": "decbytes" }
   ],
   "targets": [
    {
     "dimensions": { "LogGroupName": "*" },
     "expression": "REMOVE_EMPTY(SEARCH('{AWS/Logs,LogGroupName} MetricName=\"IncomingBytes\"', 'Sum', $period))/$period",
     "metricName": "IncomingLogEvents",
     "namespace": "AWS/Logs",
     "period": "$period",
     "region": "$region",
     "statistics": [ "Sum" ]
    }
   ]
  },
  {
   "title": "Delivery errors [count]",
   "type": "graph",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 16 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "dimensions": { "LogGroupName": "*" },
     "metricName": "DeliveryErrors",
     "namespace": "AWS/Logs",
     "period": "$period",
     "region": "$region",
     "statistics": [ "Sum" ]
    }
   ]
  },
  {
   "title": "Delivery throttling [count]",
   "type": "graph",
   "gridPos": { "h": 9, "w": 12, "x": 12, "y": 16 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "dimensions": { "LogGroupName": "*" },
     "metricName": "DeliveryThrottling",
     "namespace": "AWS/Logs",
     "period": "$period",
     "region": "$region",
     "statistics": [ "Sum" ]
    }
   ]
  },
  {
   "title": "Forwarded log events [count/sec]",
   "type": "graph",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 25 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "dimensions": { "LogGroupName": "*" },
     "expression": "REMOVE_EMPTY(SEARCH('{AWS/Logs,LogGroupName} MetricName=\"ForwardedLogEvents\"', 'Sum', $period))/$period",
     "metricName": "ForwardedLogEvents",
     "namespace": "AWS/Logs",
     "period": "$period",
     "region": "$region",
     "statistics": [ "Sum" ]
    }
   ]
  },
  {
   "title": "Forwarded bytes [bytes/sec]",
   "type": "graph",
   "gridPos": { "h": 9, "w": 12, "x": 12, "y": 25 },
   "yaxes": [
    { "format": "decbytes" }
   ],
   "targets": [
    {
     "dimensions": { "LogGroupName": "*" },
     "expression": "REMOVE_EMPTY(SEARCH('{AWS/Logs,LogGroupName} MetricName=\"ForwardedBytes\"', 'Sum', $period))/$period",
     "metricName": "ForwardedBytes",
     "namespace": "AWS/Logs",
     "period": "$period",
     "region": "$region",
     "statistics": [ "Sum" ]
    }
   ]
  }
 ]
}